@csharp_todo_backend_HostAddress = http://localhost:5206

GET {{csharp_todo_backend_HostAddress}}/api/todos
Accept: application/json

###

GET {{csharp_todo_backend_HostAddress}}/api/todos/eb20395c-dcdb-4e8b-a02e-0bd4d49b7ef9
Accept: application/json

###

POST {{csharp_todo_backend_HostAddress}}/api/todos
Content-Type: application/json

{
    "title": "New note 2",
    "notes": "Test note for dev"
}

###

PATCH {{csharp_todo_backend_HostAddress}}/api/todos/ac26ec96-1eb0-4991-8aa1-c88207257e63
Content-Type: application/json

{
    "status": 2
}
