@csharp_todo_backend_HostAddress = http://localhost:5206

GET {{csharp_todo_backend_HostAddress}}/api/todos?message=lol
Accept: application/json

###

POST {{csharp_todo_backend_HostAddress}}/api/todos
Content-Type: application/json

{
    "title": "Title",
    "notes": "Notes",
}
